name: phishsense-v2
channels:
  - conda-forge
dependencies:
- python=3.12.10
- jupyter=1.1.1
- quarto=1.7.31
- make=4.4.1
- pandas=2.2.3
- scikit-learn=1.6.1
- lxml=5.4.0
- pandera=0.23.1
- pyarrow=20.0.0
- fastparquet=2024.11.0
- pydantic=2.11.4
- xgboost=3.0.2
- altair=5.5.0
- vegafusion=2.0.2
- vl-convert-python=1.7.0
- matplotlib=3.10.3
- tabulate=0.9.0
- click=8.2.1
- scipy=1.15.2
- pip
- pip:
  - lingua-language-detector==2.1.0
  - python-whois==0.9.5
  - transformers==4.52.4
  - torch==2.7.1
  - bertopic==0.17.0
